#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: 
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 1912
POSTGRES_SQL_DB: sms

#Server
SERVER_PORT: 8080
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: <Gmail Email ID>
EMAIL_PASSWORD: <App Password>
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}